name = "vedsingh-home"
main = "src/index.js"
compatibility_date = "2026-08-12"

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
KUMA_URL = "https://status.vedsingh.com"
KUMA_SLUG = "vsnas"
JELLYFIN_URL = "https://movies.vedsingh.com"
NAVIDROME_URL = "https://music.vedsingh.com/music"
KAVITA_URL = "https://books.vedsingh.com"
AUDIOBOOKSHELF_URL = "https://audiobooks.vedsingh.com"
RETROASSEMBLY_URL = "https://games.vedsingh.com"
